import { Types } from "mongoose";

export interface IProduct {
  // map(arg0: (product: IProduct) => import("react").JSX.Element): import("react").ReactNode;
  _id: string; // Auto-generated by MongoDB
  name: string; // Product name
  description: string; // Optional product description
  price: number; // Base product price
  discount?: {
    percentage: number; // Discount percentage (e.g., 20 for 20%)
    startDate?: string; // ISO string for the discount start date
    endDate?: string; // ISO string for the discount end date
  } | null; // Discount details (optional)
  stock: number; // Available stock
  image: string; // Primary product image URL
  images?: string[]; // Additional images for the product
  category: { _id: string; name: string }; // Category object containing ID and name
  subcategory?: { _id: string; name: string }; // Optional subcategory ID
  subsubcategory?: { _id: string; name: string }; // Optional subsubcategory ID
  brand?: { _id: Types.ObjectId; name: string }; // Populated
  model?: { _id: Types.ObjectId; name: string };
  productVariantCategories?: any[]; // Array of product variant category IDs
  regionCode?: string; // Optional region-specific product code
  storageCapacity?: string; // e.g., '128GB', '256GB'
  condition?: "new" | "used"; // Product condition
  features?: string[]; // Array of product features
  isActive?: boolean; // Whether the product is active
  createdBy: string; // ID of the user/admin who created the product
  createdAt?: string; // ISO string for the creation timestamp
  updatedAt?: string; // ISO string for the last update timestamp
  rating?: number; // Average rating (0 to 5)
  wishCount?: number; // Number of users who added this to wishlist
  sold?: number; // Number of units sold
  color?: string; // Color of the product
  colorCode?: string; // HEX or RGB color code
  colors?: string[];
  colorCodes?: string[];
  size?: string; // Size details if applicable
  overview?: {description: string; images: string[]};
}

export interface GetProductsParams {
  page?: number; // Current page number
  limit?: number; // Number of products per page
  search?: string; // Search query for product name or description
  filters?: Record<string, any>; // Additional filters (category, brand, price range, etc.)
  sortBy?: string; // Field to sort by
  sortOrder?: "asc" | "desc"; // Sorting order
  categoryId?: string;
  subcategoryId?: string;
  subsubcategoryId?: string;
}

export interface CreateProductParams {
  name: string; // Product name
  description?: string; // Optional product description
  price: number; // Product price
  stock: number; // Available stock
  image: string; // Primary product image URL
  images?: string[]; // Additional product images
  category: string; // Category ID
  subcategory?: string; // Optional subcategory ID
  brand: string; // Brand ID
  model: string; // Model ID
  productVariantCategories?: string[]; // Variant category IDs
  regionCode?: string; // Optional region-specific product code
  storageCapacity?: string; // Optional storage capacity
  condition?: "new" | "used"; // Product condition
  features?: string[]; // Optional product features
  color?: string; // Color of the product
  colorCode?: string; // HEX or RGB color code
  size?: string; // Size details if applicable
  overview?: {description: string; images: string[]};
  isActive?: boolean; // Whether the product is active
  createdBy: string; // ID of the user/admin creating the product
}

export interface Product {
  _id: string; // Product ID
  name: string; // Product name
  price: number; // Product price
  stock: number; // Available stock
  image: string; // Primary image URL
  isActive?: boolean; // Whether the product is active
  createdBy: string; // ID of the user/admin creating the product
}

export interface Product {
  _id: string; // Product ID
  name: string; // Product name
  rating: number; // Average product rating (0-5)
  wishCount?: number; // Wishlist count
  sold: number; // Total units sold
  color?: string; // Product color
  colorCode?: string; // HEX or RGB color code
  size?: string; // Size details if applicable
}
